CREATE TABLE PUBLIC.USER
(
    ID              BIGSERIAL    NOT NULL,
    UUID            UUID         NOT NULL,
    ADDRESS         VARCHAR(500) NULL,
    CONTACT_NUMBER  VARCHAR(20)  NOT NULL,
    EMAIL           VARCHAR(100) NOT NULL,
    EXPIRE_DATE     TIMESTAMP    NOT NULL,
    FIRST_NAME      VARCHAR(20)  NOT NULL,
    ACTIVE          BOOLEAN      NOT NULL,
    LAST_LOGIN_TIME TIMESTAMP    NULL,
    LAST_NAME       VARCHAR(255) NOT NULL,
    LOCKED          BOOLEAN      NULL,
    PASSWORD        VARCHAR(500) NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT UX_USER__EMAIL UNIQUE (EMAIL),
    CONSTRAINT USER_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_USER__UUID UNIQUE (UUID)
);


CREATE TABLE ROLE
(
    ID          BIGSERIAL   NOT NULL,
    UUID        UUID        NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT ROLE_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_ROLE__NAME UNIQUE (NAME),
    CONSTRAINT UX_ROLE__UUID UNIQUE (UUID)
);


CREATE TABLE SITE
(
    ID          BIGSERIAL    NOT NULL,
    UUID        UUID         NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT SITE_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_SITE__DESCRIPTION UNIQUE (DESCRIPTION),
    CONSTRAINT UX_SITE__UUID UNIQUE (UUID)
);


CREATE TABLE USER_ROLE
(
    USER_ID INT8 NOT NULL,
    ROLE_ID INT8 NOT NULL,
    CONSTRAINT USER_ROLE_PKEY PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE__USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (ID),
    CONSTRAINT FK_USER_ROLE__ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);
CREATE INDEX IX_USER_ROLE__USER_ID ON PUBLIC.USER (ID);
CREATE INDEX IX_USER_ROLE__ROLE_ID ON ROLE (ID);


CREATE TABLE USER_SITE
(
    USER_ID INT8 NOT NULL,
    SITE_ID INT8 NOT NULL,
    CONSTRAINT USER_SITE_PKEY PRIMARY KEY (USER_ID, SITE_ID),
    CONSTRAINT FK_USER_SITE__USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (ID),
    CONSTRAINT FK_USER_SITE__SITE_ID FOREIGN KEY (SITE_ID) REFERENCES SITE (ID)
);
CREATE INDEX IX_USER_SITE__USER_ID ON PUBLIC.USER (ID);
CREATE INDEX IX_USER_SITE__SITE_ID ON SITE (ID);


CREATE TABLE ITEM_TYPE
(
    ID          BIGSERIAL    NOT NULL,
    UUID        UUID         NOT NULL,
    ACTIVE      BOOLEAN      NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT ITEM_TYPE_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_ITEM_TYPE__UUID UNIQUE (UUID),
    CONSTRAINT UX_ITEM_TYPE__NAME_ACTIVE UNIQUE (NAME, ACTIVE)
);


CREATE TABLE ITEM
(
    ID                 BIGSERIAL    NOT NULL,
    UUID               UUID         NOT NULL,
    BARCODE            VARCHAR(50)  NOT NULL,
    ACTIVE             BOOLEAN      NOT NULL,
    ITEM_DESCRIPTION   VARCHAR(255) NULL,
    MIN_STOCK_QUANTITY INT4         NOT NULL,
    STORE_PART_NUMBER  VARCHAR(255) NOT NULL,
    UNIT               VARCHAR(20)  NOT NULL,
    ITEM_TYPE_ID       INT8         NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT ITEM_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_ITEM__STORE_PART_NUMBER UNIQUE (STORE_PART_NUMBER),
    CONSTRAINT UX_ITEM__UUID UNIQUE (UUID),
    CONSTRAINT UX_ITEM__BARCODE UNIQUE (BARCODE),

    CONSTRAINT FK_ITEM__ITEM_TYPE_ID FOREIGN KEY (ITEM_TYPE_ID) REFERENCES ITEM_TYPE (ID)

);
CREATE INDEX IX_ITEM__ITEM_TYPE_ID ON ITEM (ITEM_TYPE_ID);


CREATE TABLE ITEM_ATTRIBUTE
(
    ID          BIGSERIAL   NOT NULL,
    UUID        UUID        NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT ITEM_ATTRIBUTE_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_ITEM_ATTRIBUTE__NAME UNIQUE (NAME),
    CONSTRAINT UX_ITEM_ATTRIBUTE__UUID UNIQUE (UUID)
);


CREATE TABLE ITEM_ATTRIBUTE_VALUE
(
    ID                BIGSERIAL   NOT NULL,
    UUID              UUID        NOT NULL,
    VALUE             VARCHAR(20) NOT NULL,
    ITEM_ATTRIBUTE_ID INT8        NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT ITEM_ATTRIBUTE_VALUE_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_ITEM_ATTR_VALUE__VALUE__ID UNIQUE (VALUE, ITEM_ATTRIBUTE_ID),
    CONSTRAINT UX_ITEM_ATTRIBUTE_VALUE__UUID UNIQUE (UUID),
    CONSTRAINT FK_ITEM_ATTRIBUTE_VALUE__ITEM_ATTR_ID FOREIGN KEY (ITEM_ATTRIBUTE_ID) REFERENCES ITEM_ATTRIBUTE (ID)

);
CREATE INDEX IX_ITEM_ATTRIBUTE_VALUE__ITEM_ATTRIBUTE_ID ON ITEM_ATTRIBUTE_VALUE (ITEM_ATTRIBUTE_ID);


CREATE TABLE ITEM_TYPE_ATTRIBUTE
(
    ID                BIGSERIAL   NOT NULL,
    UUID              UUID        NOT NULL,
    ITEM_ATTRIBUTE_ID INT8        NULL,
    ITEM_TYPE_ID      INT8        NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT ITEM_TYPE_ATTRIBUTE_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_ITEM_TYPE_ATTRIBUTE__UUID UNIQUE (UUID),

    CONSTRAINT FK_ITEM_TYPE_ATTRIBUTE__ITEM_ATTRIBUTE_ID FOREIGN KEY (ITEM_ATTRIBUTE_ID) REFERENCES ITEM_ATTRIBUTE (ID),
    CONSTRAINT FK_ITEM_TYPE_ATTRIBUTE__ITEM_TYPE_ID FOREIGN KEY (ITEM_TYPE_ID) REFERENCES ITEM_TYPE (ID)

);
CREATE INDEX IX_ITEM_TYPE_ATTRIBUTE__ITEM_ATTRIBUTE_ID ON ITEM_TYPE_ATTRIBUTE (ITEM_ATTRIBUTE_ID);
CREATE INDEX IX_ITEM_TYPE_ATTRIBUTE__ITEM_TYPE_ID ON ITEM_TYPE_ATTRIBUTE (ITEM_TYPE_ID);


CREATE TABLE ITEM_ATTRIBUTE_LIST
(
    ID                 BIGSERIAL   NOT NULL,
    UUID               UUID        NOT NULL,
    ITEM_ID            INT8        NOT NULL,
    ATTRIBUTE_ID       INT8        NOT NULL,
    ATTRIBUTE_VALUE_ID INT8        NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT ITEM_ATTRIBUTE_LIST_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_ITEM_ATTRIBUTE_LIST__UUID UNIQUE (UUID),

    CONSTRAINT FK_ITEM_ATTRIBUTE_LIST__ATTRIBUTE_ID FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ITEM_ATTRIBUTE (ID),
    CONSTRAINT FK_ITEM_ATTRIBUTE_LIST__ATTRIBUTE_VALUE_ID FOREIGN KEY (ATTRIBUTE_VALUE_ID) REFERENCES ITEM_ATTRIBUTE_VALUE (ID),
    CONSTRAINT FK_ITEM_ATTRIBUTE_LIST__ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)

);
CREATE INDEX IX_ITEM_ATTRIBUTE_LIST__ATTRIBUTE_ID ON ITEM_ATTRIBUTE_LIST (ATTRIBUTE_ID);
CREATE INDEX IX_ITEM_ATTRIBUTE_LIST__ATTRIBUTE_VALUE_ID ON ITEM_ATTRIBUTE_LIST (ATTRIBUTE_VALUE_ID);
CREATE INDEX IX_ITEM_ATTRIBUTE_LIST__ITEM_ID ON ITEM_ATTRIBUTE_LIST (ITEM_ID);


CREATE TABLE SUPPLIER
(
    ID              BIGSERIAL    NOT NULL,
    UUID            UUID         NOT NULL,
    ADDRESS         VARCHAR(300) NOT NULL,
    ACTIVE          BOOLEAN      NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    REGISTER_NUMBER VARCHAR(70)  NOT NULL,
    TAX_NUMBER      VARCHAR(70)  NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT SUPPLIER_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_SUPPLIER__TAX_NUMBER UNIQUE (TAX_NUMBER),
    CONSTRAINT UX_SUPPLIER__NAME UNIQUE (NAME),
    CONSTRAINT UX_SUPPLIER__REGISTER_NUMBER UNIQUE (REGISTER_NUMBER),
    CONSTRAINT UX_SUPPLIER__UUID UNIQUE (UUID)
);


CREATE TABLE PUBLIC.ORDER
(
    ID                  BIGSERIAL      NOT NULL,
    UUID                UUID           NOT NULL,
    ADDRESS_DETAIL      VARCHAR(500)   NULL,
    DISCOUNT_TOTAL      NUMERIC(19, 4) NULL,
    GRAND_TOTAL         NUMERIC(19, 4) NULL,
    INVOICE_DATE        TIMESTAMP      NULL,
    INVOICE_NUMBER      VARCHAR(50)    NULL,
    ACTIVE              BOOLEAN        NOT NULL,
    ORDER_CREATION_DATE TIMESTAMP      NULL,
    ORDER_NUMBER        VARCHAR(50)    NULL,
    REFERENCE_NUMBER    VARCHAR(50)    NULL,
    REJECTION_REASON    VARCHAR(255)   NULL,
    REQUEST_DATE        TIMESTAMP      NULL,
    REQUEST_NUMBER      VARCHAR(50)    NOT NULL,
    STATUS              VARCHAR(50)   NULL,
    TAX_TOTAL           NUMERIC(19, 4) NULL,
    TOTAL_QUANTITY      NUMERIC(19, 4) NULL,
    SITE_ID             INT8           NOT NULL,
    SUPPLIER_ID         INT8           NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT ORDER_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_ORDER__UUID UNIQUE (UUID),
    CONSTRAINT FK_ORDER__SITE_ID FOREIGN KEY (SITE_ID) REFERENCES SITE (ID),
    CONSTRAINT FK_ORDER__SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (ID)
);
CREATE INDEX IX_ORDER__SITE_ID ON PUBLIC.ORDER (SITE_ID);
CREATE INDEX IX_ORDER__SUPPLIER_ID ON PUBLIC.ORDER (SUPPLIER_ID);


CREATE TABLE ORDER_HISTORY
(
    ID          BIGSERIAL    NOT NULL,
    UUID        UUID         NOT NULL,
    DESCRIPTION VARCHAR(200) NULL,
    STATUS      VARCHAR(255) NULL,
    ORDER_ID    INT8         NOT NULL,
    USER_ID     INT8         NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT ORDER_HISTORY_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_ORDER_HISTORY__UUID UNIQUE (UUID),
    CONSTRAINT FK_ORDER_HISTORY__ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES PUBLIC.ORDER (ID),
    CONSTRAINT FK_ORDER_HISTORY__USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.ORDER (ID)
);
CREATE INDEX IX_ORDER_HISTORY__ORDER_ID ON ORDER_HISTORY (ORDER_ID);
CREATE INDEX IX_ORDER_HISTORY__USER_ID ON ORDER_HISTORY (USER_ID);


CREATE TABLE ORDER_ITEM
(
    ID               BIGSERIAL      NOT NULL,
    UUID             UUID           NOT NULL,
    BARCODE          VARCHAR(50)    NOT NULL,
    DESCRIPTION      VARCHAR(255)   NULL,
    DISCOUNT_PERCENT NUMERIC(19, 4) NULL,
    ACTIVE           BOOLEAN        NOT NULL,
    QUANTITY         NUMERIC(19, 4) NULL,
    TAX_PERCENT      NUMERIC(19, 4) NULL,
    TAX_TOTAL        NUMERIC(19, 4) NULL,
    TOTAL            NUMERIC(19, 4) NULL,
    TOTAL_QUANTITY   NUMERIC(19, 4) NULL,
    UNIT             VARCHAR(20)    NOT NULL,
    UNIT_PRICE       NUMERIC(19, 4) NULL,
    APPROVE_QUANTITY NUMERIC(19, 4) NULL,
    APPROVE          BOOLEAN        NOT NULL,
    ITEM_ID          INT8           NOT NULL,
    ORDER_ID         INT8           NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT ORDER_ITEM_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_ORDER_ITEM__UUID UNIQUE (UUID),
    CONSTRAINT FK_ORDER_ITEM__ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID),
    CONSTRAINT FK_ORDER_ITEM__ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES PUBLIC.ORDER (ID)
);
CREATE INDEX IX_ORDER_ITEM__ITEM_ID ON ORDER_ITEM (ITEM_ID);
CREATE INDEX IX_ORDER_ITEM__ORDER_ID ON ORDER_ITEM (ORDER_ID);


CREATE TABLE VEHICLE_TYPE
(
    ID          BIGSERIAL   NOT NULL,
    UUID        UUID        NOT NULL,
    ACTIVE      BOOLEAN     NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT UX_VEHICLE_TYPE__UUID UNIQUE (UUID),
    CONSTRAINT UX_VEHICLE_TYPE__NAME_ACTIVE UNIQUE (NAME, ACTIVE),
    CONSTRAINT VEHICLE_TYPE_PKEY PRIMARY KEY (ID)
);


CREATE TABLE VEHICLE
(
    ID                     BIGSERIAL   NOT NULL,
    UUID                   UUID        NOT NULL,
    FLEET_NO               VARCHAR(50) NULL,
    SITE_ID                INT8        NOT NULL,
    REGISTRATION_NO        VARCHAR(50) NULL,
    SERIAL_NO              VARCHAR(50) NULL,
    UNIT                   VARCHAR(20) NULL,
    VIN_NO                 VARCHAR(50) NULL,
    ACTIVE                 BOOLEAN     NOT NULL,
    USABLE                 BOOLEAN     NOT NULL,
    LAST_SERVICE_DAY       VARCHAR(20) NULL,
    LAST_SERVICE_HOURS     VARCHAR(20) NULL,
    SERVICE_INTERVAL_HOURS VARCHAR(20) NULL,
    CURRENT_MACHINE_HOURS  VARCHAR(50) NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    VEHICLE_TYPE_ID        INT8        NOT NULL,
    CONSTRAINT UX_VEHICLE__FLEET_NO UNIQUE (FLEET_NO),
    CONSTRAINT UX_VEHICLE__UUID UNIQUE (UUID),
    CONSTRAINT VEHICLE_PKEY PRIMARY KEY (ID),
    CONSTRAINT FK_VEHICLE__SITE_ID FOREIGN KEY (SITE_ID) REFERENCES SITE (ID),
    CONSTRAINT FK_VEHICLE__VEHICLE_TYPE_ID FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE (ID)
);
CREATE INDEX IX_VEHICLE__SITE_ID ON VEHICLE (SITE_ID);
CREATE INDEX IX_VEHICLE__FLEET_SITE ON VEHICLE (FLEET_NO, SITE_ID);
CREATE INDEX IX_VEHICLE__VEHICLE_TYPE_ID ON VEHICLE (VEHICLE_TYPE_ID);


CREATE TABLE VEHICLE_ATTRIBUTE
(
    ID          BIGSERIAL   NOT NULL,
    UUID        UUID        NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT UX_VEHICLE_ATTRIBUTE__NAME UNIQUE (NAME),
    CONSTRAINT UX_VEHICLE_ATTRIBUTE__UUID UNIQUE (UUID),
    CONSTRAINT VEHICLE_ATTRIBUTE_PKEY PRIMARY KEY (ID)
);


CREATE TABLE VEHICLE_ATTRIBUTE_VALUE
(
    ID                   BIGSERIAL   NOT NULL,
    UUID                 UUID        NOT NULL,
    VALUE                VARCHAR(20) NOT NULL,
    VEHICLE_ATTRIBUTE_ID INT8        NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT UX_VEHICLE_ATTRIBUTE_VALUE__UUID UNIQUE (UUID),
    CONSTRAINT UX_VEHICLE_ATTRIBUTE_VALUE__VALUE__ATTR_ID UNIQUE (VALUE, VEHICLE_ATTRIBUTE_ID),
    CONSTRAINT VEHICLE_ATTRIBUTE_VALUE_PKEY PRIMARY KEY (ID),
    CONSTRAINT FK_VEHICLE_ATTRIBUTE_VALUE__VEHICLE_ATTRIBUTE_ID FOREIGN KEY (VEHICLE_ATTRIBUTE_ID) REFERENCES VEHICLE_ATTRIBUTE (ID)
);
CREATE INDEX IX_VEHICLE_ATTRIBUTE_VALUE__VEHICLE_ATTRIBUTE_ID ON VEHICLE_ATTRIBUTE_VALUE (VEHICLE_ATTRIBUTE_ID);


CREATE TABLE VEHICLE_TYPE_ATTRIBUTE
(
    ID                   BIGSERIAL   NOT NULL,
    UUID                 UUID        NOT NULL,
    VEHICLE_ATTRIBUTE_ID INT8        NOT NULL,
    VEHICLE_TYPE_ID      INT8        NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT UX_VEHICLE_TYPE_ATTRIBUTE__UUID UNIQUE (UUID),
    CONSTRAINT VEHICLE_TYPE_ATTRIBUTE_PKEY PRIMARY KEY (ID),
    CONSTRAINT FK_VEHICLE_TYPE_ATTRIBUTE__VEHICLE_ATTRIBUTE_ID FOREIGN KEY (VEHICLE_ATTRIBUTE_ID) REFERENCES VEHICLE_ATTRIBUTE (ID),
    CONSTRAINT FK_VEHICLE_TYPE_ATTRIBUTE__VEHICLE_TYPE_ID FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE (ID)
);
CREATE INDEX IX_VEHICLE_TYPE_ATTRIBUTE__VEHICLE_ATTRIBUTE_ID ON VEHICLE_TYPE_ATTRIBUTE (VEHICLE_ATTRIBUTE_ID);
CREATE INDEX IX_VEHICLE_TYPE_ATTRIBUTE__VEHICLE_TYPE_ID ON VEHICLE_TYPE_ATTRIBUTE (VEHICLE_TYPE_ID);


CREATE TABLE VEHICLE_ATTRIBUTE_LIST
(
    ID                 BIGSERIAL   NOT NULL,
    UUID               UUID        NOT NULL,
    VEHICLE_ID         INT8        NOT NULL,
    ATTRIBUTE_ID       INT8        NOT NULL,
    ATTRIBUTE_VALUE_ID INT8        NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT UX_VEHICLE_ATTRIBUTE_LIST__UUID UNIQUE (UUID),
    CONSTRAINT VEHICLE_ATTRIBUTE_LIST_PKEY PRIMARY KEY (ID),
    CONSTRAINT FK_VEHICLE_ATTRIBUTE_LIST__ATTRIBUTE_ID FOREIGN KEY (ATTRIBUTE_ID) REFERENCES VEHICLE_ATTRIBUTE (ID),
    CONSTRAINT FK_VEHICLE_ATTRIBUTE_LIST__ATTRIBUTE_VALUE_ID FOREIGN KEY (ATTRIBUTE_VALUE_ID) REFERENCES VEHICLE_ATTRIBUTE_VALUE (ID),
    CONSTRAINT FK_VEHICLE_ATTRIBUTE_LIST__VEHICLE_ID FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (ID)
);
CREATE INDEX IX_VEHICLE_ATTRIBUTE_LIST__ATTRIBUTE_ID ON VEHICLE_ATTRIBUTE_LIST (ATTRIBUTE_ID);
CREATE INDEX IX_VEHICLE_ATTRIBUTE_LIST__ATTRIBUTE_VALUE_ID ON VEHICLE_ATTRIBUTE_LIST (ATTRIBUTE_VALUE_ID);
CREATE INDEX IX_VEHICLE_ATTRIBUTE_LIST__VEHICLE_ID ON VEHICLE_ATTRIBUTE_LIST (VEHICLE_ID);


CREATE TABLE CONTACT
(
    ID          BIGSERIAL    NOT NULL,
    UUID        UUID         NOT NULL,
    EMAIL       VARCHAR(120) NULL,
    ACTIVE      BOOLEAN      NOT NULL,
    LAND_LINE   VARCHAR(20)  NULL,
    NAME        VARCHAR(100) NOT NULL,
    PHONE_NO    VARCHAR(20)  NULL,
    ROLE        VARCHAR(50)  NULL,
    SUPPLIER_ID INT8         NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT CONTACT_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_CONTACT__NAME UNIQUE (NAME),
    CONSTRAINT UX_CONTACT__UUID UNIQUE (UUID),
    CONSTRAINT FK_CONTACT__SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (ID)
);
CREATE INDEX IX_CONTACT__SUPPLIER_ID ON CONTACT (SUPPLIER_ID);


CREATE TABLE IMAGE
(
    ID          BIGSERIAL    NOT NULL,
    UUID        UUID         NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    SIZE        INT8         NULL,
    SELECTED    BOOLEAN      NOT NULL,
    ITEM_ID     INT8         NULL,
    USER_ID     INT8         NULL,
    VEHICLE_ID  INT8         NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT IMAGE_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_IMAGE__UUID UNIQUE (UUID),

    CONSTRAINT FK_IMAGE__ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID),
    CONSTRAINT FK_IMAGE__USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (ID),
    CONSTRAINT FK_IMAGE__VEHICLE_ID FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (ID)

);
CREATE INDEX IX_IMAGE__ITEM_ID ON IMAGE (ITEM_ID);
CREATE INDEX IX_IMAGE__USER_ID ON IMAGE (USER_ID);
CREATE INDEX IX_IMAGE__VEHICLE_ID ON IMAGE (VEHICLE_ID);

INSERT INTO PUBLIC.USER(ID, CREATED_AT, CREATED_BY, MODIFIED_AT, MODIFIED_BY, UUID, PASSWORD, ADDRESS, CONTACT_NUMBER,
                        EMAIL, EXPIRE_DATE, FIRST_NAME, ACTIVE, LAST_LOGIN_TIME, LAST_NAME, LOCKED)
VALUES (NEXTVAL('USER_ID_SEQ'), '2019-07-22 00:23:57.726', CURRVAL('USER_ID_SEQ'), NULL, NULL,
        '313be66a-f7c8-491c-9fcd-3330f9446109',
        '$2a$10$briit.wTfRthNyxv/T6CPOVHGvyDN0S1Y66Cm.zUe4Ik05GFkqzoi', NULL, '111', 'opsicol@hqtech.com',
        '2019-07-22 00:23:57.726', 'admin', TRUE, NULL, 'admin', FALSE);

INSERT INTO ROLE (ID, CREATED_AT, MODIFIED_AT, UUID, NAME, CREATED_BY, MODIFIED_BY)
VALUES (NEXTVAL('ROLE_ID_SEQ'), '2019-08-01 00:00:00.000', NULL,
        '313be66a-f7c8-491c-9fcd-3330f9446109', 'ROLE_ADMIN', CURRVAL('USER_ID_SEQ'), NULL);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES (1, 1);

INSERT INTO SITE (ID, CREATED_AT, MODIFIED_AT, UUID, DESCRIPTION, CREATED_BY, MODIFIED_BY)
VALUES (NEXTVAL('SITE_ID_SEQ'), '2019-09-09 00:00:00.000', NULL,
        '313be66a-f7c8-491c-9fcd-3330f9446109', 'SITE 1', CURRVAL('USER_ID_SEQ'), NULL);

INSERT INTO USER_SITE (USER_ID, SITE_ID)
VALUES (CURRVAL('USER_ID_SEQ'), CURRVAL('SITE_ID_SEQ'));
