CREATE TABLE PROPERTY
(
    ID          BIGSERIAL   NOT NULL,
    UUID        UUID        NOT NULL,
    GROUP_NAME  VARCHAR(50) NOT NULL,
    KEY_LABEL   VARCHAR(50) NOT NULL,
    KEY_VALUE   VARCHAR(50) NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT PROPERTY_PKEY PRIMARY KEY (ID),
    CONSTRAINT UX_PROPERTY__GROUP_KEY UNIQUE (GROUP_NAME, KEY_LABEL),
    CONSTRAINT UX_PROPERTY__UUID UNIQUE (UUID)
);

INSERT INTO PROPERTY (ID, CREATED_AT, MODIFIED_AT, UUID, GROUP_NAME, KEY_LABEL, KEY_VALUE, CREATED_BY, MODIFIED_BY)
VALUES (NEXTVAL('PROPERTY_ID_SEQ'), '2019-01-01 00:00:00.000', NULL, '21a9d26f-6412-4fdf-a0ed-4891762a5a58', 'UNIT',
        'KG', 'KG', 1, NULL);
INSERT INTO PROPERTY (ID, CREATED_AT, MODIFIED_AT, UUID, GROUP_NAME, KEY_LABEL, KEY_VALUE, CREATED_BY, MODIFIED_BY)
VALUES (NEXTVAL('PROPERTY_ID_SEQ'), '2019-09-01 00:00:00.000', NULL, '0fece4e1-edb3-4779-b7b0-154130648402', 'UNIT',
        'LITRES', 'LITERS', 1, NULL);
