CREATE TABLE MESSAGE
(
    ID            BIGSERIAL     NOT NULL,
    UUID          UUID          NOT NULL,
    ORDER_ITEM_ID INT8          NULL,
    MESSAGE       VARCHAR(2000) NOT NULL,
    CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
    CONSTRAINT MESSAGE_PKEY PRIMARY KEY (ID),
    CONSTRAINT MESSAGE__UUID UNIQUE (UUID),
    CONSTRAINT FK_MESSAGE__ORDER_ITEM_ID FOREIGN KEY (ORDER_ITEM_ID) REFERENCES ORDER_ITEM (ID)
);
CREATE INDEX IX_MESSAGE__ORDER_ITEM_ID ON MESSAGE (ORDER_ITEM_ID);
