CREATE TABLE STOCK (
	ID BIGSERIAL NOT NULL,
	UUID UUID NOT NULL,
	QUANTITY NUMERIC(19,4) NOT NULL,
	ITEM_ID INT8 NOT NULL,
	SITE_ID INT8 NOT NULL,
	CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
	CONSTRAINT STOCK_PKEY PRIMARY KEY (ID),
	CONSTRAINT UX_STOCK__UUID UNIQUE (UUID),
	CONSTRAINT FK_STOCK__SITE_ID FOREIGN KEY (SITE_ID) REFERENCES SITE (ID),
	CONSTRAINT FK_STOCK__ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);

CREATE INDEX IX_STOCK__ITEM_ID ON PUBLIC.STOCK (ITEM_ID);
CREATE INDEX IX_STOCK__SITE_ID ON PUBLIC.STOCK (SITE_ID);


CREATE TABLE STOCK_HISTORY (
	ID BIGSERIAL NOT NULL,
	UUID UUID NOT NULL,
	QUANTITY NUMERIC(19,4) NOT NULL,
	TYPE VARCHAR(50) NOT NULL,
	ITEM_ID INT8 NOT NULL,
	ORDER_ITEM_ID INT8 NULL,
	SOURCE_SITE_ID INT8 NULL,
	TARGET_SITE_ID INT8 NULL,
	CREATED_BY      INT8         NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL,
    MODIFIED_BY     INT8         NULL,
    MODIFIED_AT     TIMESTAMP    NULL,
	CONSTRAINT STOCK_HISTORY_PKEY PRIMARY KEY (ID),
	CONSTRAINT UX_STOCK_HISTORY__UUID UNIQUE (UUID),
	CONSTRAINT FK_STOCK_HISTORY__ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID),
	CONSTRAINT FK_STOCK_HISTORY__ORDER_ITEM_ID FOREIGN KEY (ORDER_ITEM_ID) REFERENCES ORDER_ITEM (ID),
	CONSTRAINT FK_STOCK_HISTORY__SOURCE_SITE_ID FOREIGN KEY (SOURCE_SITE_ID) REFERENCES SITE (ID),
	CONSTRAINT FK_STOCK_HISTORY__TARGET_SITE_ID FOREIGN KEY (TARGET_SITE_ID) REFERENCES SITE (ID)
);

CREATE INDEX IX_STOCK_HISTORY__ITEM_ID ON STOCK_HISTORY (ITEM_ID);
CREATE INDEX IX_STOCK_HISTORY__ORDER_ITEM_ID ON STOCK_HISTORY  (ORDER_ITEM_ID);
CREATE INDEX IX_STOCK_HISTORY__SOURCE_SITE_ID ON STOCK_HISTORY (SOURCE_SITE_ID);
CREATE INDEX IX_STOCK_HISTORY__TARGET_SITE_ID ON STOCK_HISTORY (TARGET_SITE_ID);

ALTER TABLE SITE ADD SUPPLIER_ID INT8 NULL;
CREATE INDEX IX_SITE__SUPPLIER_ID ON SITE (SUPPLIER_ID);

INSERT INTO SUPPLIER
(ID, CREATED_AT, MODIFIED_AT, UUID, ADDRESS, ACTIVE, NAME, REGISTER_NUMBER, TAX_NUMBER, CREATED_BY, MODIFIED_BY)
VALUES(NEXTVAL('SUPPLIER_ID_SEQ'), '2019-08-18 23:48:32.203', NULL, '40f5dd5c-7dcd-85d2-a248-f85c898c0ea3', 'OFFICE ADDRESS', true, 'HQTECH', '0', '0', 1, NULL);

INSERT INTO SITE (ID, CREATED_AT, MODIFIED_AT, UUID, DESCRIPTION, CREATED_BY, MODIFIED_BY, SUPPLIER_ID)
VALUES (NEXTVAL('SITE_ID_SEQ'), '2019-09-09 00:00:00.000', NULL,
        '313be66a-f7c8-491c-9fcd-3330f9448109', 'HAKANO', 1, NULL, CURRVAL('SUPPLIER_ID_SEQ'));
