ALTER TABLE STOCK ADD CONSTRAINT UX_STOCK__SITE_ITEM UNIQUE (SITE_ID, ITEM_ID);

ALTER TABLE STOCK_HISTORY ADD JOB_CARD_ITEM_ID INT8 NULL;
ALTER TABLE STOCK_HISTORY ADD CONSTRAINT FK_STOCK_HISTORY__JOB_CARD_ITEM_ID FOREIGN KEY (JOB_CARD_ITEM_ID) REFERENCES JOB_CARD_ITEM(ID);

ALTER TABLE STOCK_HISTORY ADD TRANSFER_ITEM_ID INT8 NULL;
ALTER TABLE STOCK_HISTORY ADD CONSTRAINT FK_STOCK_HISTORY__TRANSFER_ITEM_ID FOREIGN KEY (TRANSFER_ITEM_ID) REFERENCES TRANSFER_ITEM(ID);
