ALTER TABLE STOCK_HISTORY ADD RECEIVED_USER_ID INT8 NULL;
ALTER TABLE STOCK_HISTORY ADD CONSTRAINT FK_STOCK_HISTORY__RECEIVED_USER_ID FOREIGN KEY (RECEIVED_USER_ID) REFERENCES PUBLIC.USER(ID);
CREATE INDEX IX_STOCK_HISTORY__RECEIVED_USER_ID ON STOCK_HISTORY USING BTREE (RECEIVED_USER_ID);

CREATE INDEX IX_STOCK_HISTORY__JOB_CARD_ITEM_ID ON STOCK_HISTORY USING BTREE (JOB_CARD_ITEM_ID);
CREATE INDEX IX_STOCK_HISTORY__TRANSFER_ITEM_ID ON STOCK_HISTORY USING BTREE (TRANSFER_ITEM_ID);
