ALTER TABLE ORDER_HISTORY DROP CONSTRAINT FK_ORDER_HISTORY__USER_ID;
ALTER TABLE ORDER_HISTORY ADD CONSTRAINT FK_ORDER_HISTORY__USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER(ID);

CREATE TABLE ORDER_ITEM_DETAIL (
	ID BIGSERIAL NOT NULL,
	UUID UUID NOT NULL,
	DESCRIPTION VARCHAR(500) NULL,
	QUANTITY NUMERIC(19,4) NULL,
	ORDER_ITEM_ID INT8 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	CREATED_BY INT8 NOT NULL,
	MODIFIED_AT TIMESTAMP NULL,
	MODIFIED_BY INT8 NULL,
	CONSTRAINT ORDER_ITEM_DETAIL_PKEY PRIMARY KEY (ID),
	CONSTRAINT UX_ORDER_ITEM_DETAIL_UUID UNIQUE (UUID),
	CONSTRAINT FK__ORDER_ITEM_DETAIL__ORDER_ITEM_ID FOREIGN KEY (ORDER_ITEM_ID) REFERENCES ORDER_ITEM(ID)
);
CREATE INDEX IX_ORDER_ITEM_DETAIL__ORDER_ITEM_ID ON ORDER_ITEM_DETAIL USING BTREE (ORDER_ITEM_ID);
