CREATE TABLE PERMISSION (
	ID BIGSERIAL NOT NULL,
	UUID UUID NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	CREATED_BY INT8 NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	MODIFIED_BY INT8 NULL,
	MODIFIED_AT TIMESTAMP NULL,
	CONSTRAINT PERMISSION_PKEY PRIMARY KEY (ID),
	CONSTRAINT UX_PERMISSION__NAME UNIQUE ("name"),
	CONSTRAINT UX_PERMISSION__UUID UNIQUE (UUID)
);
CREATE INDEX IX_PERMISSION__PERMISSION_ID ON PERMISSION USING BTREE (ID);

 CREATE TABLE ROLE_PERMISSION (
	ROLE_ID INT8 NOT NULL,
	PERMISSION_ID INT8 NOT NULL
);
