ALTER TABLE IMAGE ADD SUPPLIER_ID INT8 NULL;
ALTER TABLE PUBLIC.IMAGE ADD CONSTRAINT FK_IMAGE__SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID);
CREATE INDEX IX_IMAGE__SUPPLIER_ID ON IMAGE USING BTREE (SUPPLIER_ID);
