CREATE TABLE FIELD_ATTRIBUTE
(
    ID            BIGSERIAL     NOT NULL,
    UUID          UUID          NOT NULL,
    FIELD_ID      VARCHAR(50)   NOT NULL,
    LABEL         VARCHAR(50)   NOT NULL,
    TITLE         VARCHAR(200)   NOT NULL,
    CREATED_BY    INT8         NOT NULL,
    CREATED_AT    TIMESTAMP    NOT NULL,
    MODIFIED_BY   INT8         NULL,
    MODIFIED_AT   TIMESTAMP    NULL,
    CONSTRAINT FIELD_ATTRIBUTE_ID_PKEY PRIMARY KEY (ID),
    CONSTRAINT FIELD_ATTRIBUTE__UUID UNIQUE (UUID)
);
CREATE INDEX IX_FIELD_ATTRIBUTE__FIELD_ID ON FIELD_ATTRIBUTE (FIELD_ID);
